import Home from './Home';
import Login from './Login';
import MusicSearchField from './MusicSearchField';
import Profile from './Profile';
import CommunityPost from './CommunityPost';
import CreatePost from './CreatePost';
import SearchPage from './SearchPage';
import musicPage from './musicPage';
import ArtistPage from './ArtistPage';
import SavedMusic from './SavedMusic';
import Register from './Register';
export { Home, Login, MusicSearchField, Profile,CommunityPost,CreatePost,SearchPage,musicPage,ArtistPage,SavedMusic,Register};